// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnWBCvEQ_8r6hC7BxRLIAsC-sWPz0RNI8',
    appId: '1:514524285235:android:9c7af02e424c95d8791646',
    messagingSenderId: '514524285235',
    projectId: 'collosian-cleaner-service-app',
    databaseURL: 'https://collosian-cleaner-service-app-default-rtdb.firebaseio.com',
    storageBucket: 'collosian-cleaner-service-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQi5qBoHHjkCASwrup7yXwCO6nMU5kfQ',
    appId: '1:514524285235:ios:9b3f2524ece9e2b0791646',
    messagingSenderId: '514524285235',
    projectId: 'collosian-cleaner-service-app',
    databaseURL: 'https://collosian-cleaner-service-app-default-rtdb.firebaseio.com',
    storageBucket: 'collosian-cleaner-service-app.firebasestorage.app',
    iosBundleId: 'io.ccs.app',
  );

}